Traceback (most recent call last):
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\alans\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\alans\AppData\Local\pypoetry\Cache\virtualenvs\cipher-xs2441-GvwusASK-py3.9\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cipher_xs2441

print(cipher_xs2441.__version__)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_12200/2813266838.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mcipher_xs2441[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mprint[0m[1;33m([0m[0mcipher_xs2441[0m[1;33m.[0m[0m__version__[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'cipher_xs2441'
ModuleNotFoundError: No module named 'cipher_xs2441'

